id = "hello-world-zed-extension"
name = "Hello World Zed Extension"
version = "0.0.1"
schema_version = 1
authors = ["David Sillman <dsillman2000@gmail.com>"]
description = "My cool extension"
repository = "https://github.com/dsillman2000/hello-world-zed-extension"

[context_servers.mcp-hello-world]
name = "Hello World MCP Server"
